### PR TITLE
Final define the private room

### PR DESCRIPTION
**Pull request by marvin5064**
Add new GUI component for handle input of password of private room.

### CODE REVIEW

**Comment by marvin5064** [comment]
Enter a normal room directly as before iff the room existing in the roomList
image
Enter a private room, requires password
image
If empty pw field:
image
Wrong pw:
image
Right pw will close the dialog, and your can enter the room same as normal room

**Comment by marvin5064** [comment]
My desired data structure in firebase:
image

**Comment by yps1994** [comment]
As discussed, I will hold the PR until we finished the discussion tomorrow, because there are too many changes in the data structure.

**Comment by magickaichen** [comment]
My idea is to keep our structure like roomList/roomID: isPrivate = true or false
                                                                                      password (will add this attribute if isPrivate = true)
                                                                                      questions/question1,question2...

**Pull request merged**
